version: "3.8"

services:
  envoy_first:
    build: ./envoy1
    ports:
      - "9095:9095"
    networks:
      - proxy_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "500M"  
        reservations:
          cpus: "1"
          memory: "500M"


  envoy-second:
    build: ./envoy2
    ports:
      - "9096:9096"
    networks:
      - proxy_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "750M"  
        reservations:
          cpus: "1.0"
          memory: "750M"

  # backend:
  #   build: ./backend
  #   ports:
  #     - "8083:8083"
  #   networks:
  #     - proxy_network
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "2.0"
  #         memory: "1G"  
  #       reservations:
  #         cpus: "2.0"
  #         memory: "1G"
  


  varnish_new:
    build: ./varnish
    ports:
      - "8080:80"
    networks:
      - proxy_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "50M" 
        reservations:
          cpus: "0.5"
          memory: "50M"
    command: 
       -s default=malloc,30M
      #  -s org2=malloc,1G


  backend:
    build: ./backend2
    ports:
      - "8083:8083"
    networks:
      - proxy_network
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - proxy_network


networks:
  proxy_network:
    driver: bridge
