apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
  namespace: my-namespace

spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy

    spec:
      containers:
      - name: envoy-second
        image: milanka00/caching:envoy-v4
        ports:
        - containerPort: 9096