apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
  namespace: my-namespace

spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy

    spec:
      containers:
      - name: additional-envoy-container
        image: milanka00/caching:envoy-v1
        ports:
        - containerPort: 9096