apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: my-namespace

spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend

    spec:
      containers:
      - name: backend-container
        image: milanka00/caching:backend-v1
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "1G"  
            cpu: "2.0"      
          limits:
            memory: "1G"  
            cpu: "2.0"      
