apiVersion: v1
kind: Service
metadata:
  name: varnish-service
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: varnish
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
  
